/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.Calendar;
import Consultas.Consultas;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Martínez Hernández Gabriela Martínez Carrera Dulce Carolina
 */
public class Actualizar_grupo extends javax.swing.JFrame {

    Consultas consultas = new Consultas();
    String[] nombreUsuarios;
    /**
     * Creates new form actualizar_grupo
     */
    public Actualizar_grupo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eti_titulo = new javax.swing.JLabel();
        eti_periodo = new javax.swing.JLabel();
        eti_año = new javax.swing.JLabel();
        eti_materia = new javax.swing.JLabel();
        eti_grupo = new javax.swing.JLabel();
        eti_hora = new javax.swing.JLabel();
        btn_guardar_cambios = new javax.swing.JButton();
        cmb_hora = new javax.swing.JComboBox<>();
        cmbx_periodo = new javax.swing.JComboBox<>();
        txtAnio = new javax.swing.JTextField();
        cmb_materia = new javax.swing.JComboBox<>();
        cmb_grupo = new javax.swing.JComboBox<>();
        eti_num_unidad1 = new javax.swing.JLabel();
        cmb_unidad1 = new javax.swing.JComboBox<>();
        etiquetaCurpMaestro1 = new javax.swing.JLabel();
        comboMaestros1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        eti_titulo.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        eti_titulo.setText("Actualizar Materia");

        eti_periodo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_periodo.setText("Periodo: ");

        eti_año.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_año.setText("Año:");

        eti_materia.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_materia.setText("Materia: ");

        eti_grupo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_grupo.setText("Grupo:");

        eti_hora.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_hora.setText("Hora:");

        btn_guardar_cambios.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        btn_guardar_cambios.setText("Guardar cambios");
        btn_guardar_cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_cambiosActionPerformed(evt);
            }
        });

        cmb_hora.setEditable(true);
        cmb_hora.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmb_hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00-08:00", "08:00-09:00", "09:00-10:00", "10:00-11:00", "11:00-12:00", "12:00-13:00", "13:00-14:00", "14:00-15:00", "15:00-16:00", "16:00-17:00", "17:00-18:00", "18:00-19:00", "19:00-20:00" }));
        cmb_hora.setToolTipText("");

        cmbx_periodo.setEditable(true);
        cmbx_periodo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmbx_periodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero - Junio", "Agosto - Diciembre", "Julio - Agosto" }));

        cmb_materia.setEditable(true);
        cmb_materia.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmb_materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programación orientada a objetos", "Estructura de datos", "Lenguajes de interfaz", "Agregar otra..." }));
        cmb_materia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_materiaItemStateChanged(evt);
            }
        });
        cmb_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_materiaActionPerformed(evt);
            }
        });

        cmb_grupo.setEditable(true);
        cmb_grupo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmb_grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISA", "ISB", "ISC", "ISD", "ISU" }));
        cmb_grupo.setToolTipText("");

        eti_num_unidad1.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_num_unidad1.setText("Num.Unidades");

        cmb_unidad1.setEditable(true);
        cmb_unidad1.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmb_unidad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmb_unidad1.setToolTipText("");

        etiquetaCurpMaestro1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        etiquetaCurpMaestro1.setText("Maestra/o:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btn_guardar_cambios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eti_titulo)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eti_num_unidad1)
                            .addComponent(etiquetaCurpMaestro1))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_unidad1, 0, 238, Short.MAX_VALUE)
                            .addComponent(comboMaestros1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cmb_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eti_grupo)
                                .addComponent(eti_materia)
                                .addComponent(eti_hora)
                                .addComponent(eti_periodo)
                                .addComponent(eti_año))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(cmb_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmb_materia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAnio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbx_periodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(eti_titulo)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_periodo)
                    .addComponent(cmbx_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eti_año)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_materia)
                    .addComponent(cmb_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_grupo)
                    .addComponent(cmb_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_hora)
                    .addComponent(cmb_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eti_num_unidad1)
                    .addComponent(cmb_unidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(etiquetaCurpMaestro1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(comboMaestros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btn_guardar_cambios)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Calendar calendario = Calendar.getInstance();
        Integer year = calendario.get(Calendar.YEAR);
        txtAnio.setText(String.valueOf(year));
        
        setLocationRelativeTo(null);
        txtAnio.setText(String.valueOf(year)); //Se cambia el año por el del sistema actual
        nombreUsuarios = consultas.getCurp();
        //Se rellena el combo box
        for (int i = 0; i < nombreUsuarios.length; i++) {
            comboMaestros1.addItem(nombreUsuarios[i]);
        }
    }//GEN-LAST:event_formWindowOpened

    private void cmb_materiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_materiaItemStateChanged
        if (evt.getItem() == "Agregar otra...") {
            this.dispose();
            AgregarMateria agregarMateria = new AgregarMateria();
            agregarMateria.setVisible(true);
        }
    }//GEN-LAST:event_cmb_materiaItemStateChanged

    private void cmb_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_materiaActionPerformed

    }//GEN-LAST:event_cmb_materiaActionPerformed

    private void btn_guardar_cambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_cambiosActionPerformed
        try{
            consultas.updateMateria(cmb_grupo.getSelectedItem().toString(), cmb_materia.getSelectedItem().toString(), txtAnio.getText(), cmbx_periodo.getSelectedItem().toString(), cmb_unidad1.getSelectedItem().toString(), cmb_hora.getSelectedItem().toString(),comboMaestros1.getSelectedItem().toString());
            JOptionPane.showMessageDialog(null, "Cambios guardados.");
        }catch(NullPointerException npe){
            System.out.println("Error");
        }
    }//GEN-LAST:event_btn_guardar_cambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar_grupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar_grupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar_grupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar_grupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar_grupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar_cambios;
    private javax.swing.JComboBox<String> cmb_grupo;
    private javax.swing.JComboBox<String> cmb_hora;
    private javax.swing.JComboBox<String> cmb_materia;
    private javax.swing.JComboBox<String> cmb_unidad1;
    private javax.swing.JComboBox<String> cmbx_periodo;
    private javax.swing.JComboBox<String> comboMaestros1;
    private javax.swing.JLabel eti_año;
    private javax.swing.JLabel eti_grupo;
    private javax.swing.JLabel eti_hora;
    private javax.swing.JLabel eti_materia;
    private javax.swing.JLabel eti_num_unidad1;
    private javax.swing.JLabel eti_periodo;
    private javax.swing.JLabel eti_titulo;
    private javax.swing.JLabel etiquetaCurpMaestro1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAnio;
    // End of variables declaration//GEN-END:variables
}
