/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.io.File;
import java.io.FileInputStream;
import java.util.Iterator;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import Consultas.Consultas;

/**
 *
 * @author Martínez Hernández Gabriela Martínez Carrera Dulce Carolina
 */
public class Cargar_lista extends javax.swing.JFrame {

    Consultas con = new Consultas();

    /**
     * Creates new form cargar_lista
     */
    public Cargar_lista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eti_titulo = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        eti_periodo = new javax.swing.JLabel();
        eti_año = new javax.swing.JLabel();
        eti_materia = new javax.swing.JLabel();
        eti_grupo = new javax.swing.JLabel();
        eti_hora = new javax.swing.JLabel();
        cmbx_periodo = new javax.swing.JComboBox<>();
        cmb_materia = new javax.swing.JComboBox<>();
        cmb_grupo = new javax.swing.JComboBox<>();
        cmb_hora = new javax.swing.JComboBox<>();
        cmbx_anio = new javax.swing.JComboBox<>();
        txt_direccion_excel = new javax.swing.JTextField();
        eti_cargar_lista = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        eti_titulo.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        eti_titulo.setText("Agregar Lista ");

        btn_buscar.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setMaximumSize(new java.awt.Dimension(50, 50));
        btn_buscar.setMinimumSize(new java.awt.Dimension(50, 50));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        eti_periodo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_periodo.setText("Periodo: ");

        eti_año.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_año.setText("Año:");

        eti_materia.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_materia.setText("Materia: ");

        eti_grupo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_grupo.setText("Grupo:");

        eti_hora.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_hora.setText("Hora:");

        cmbx_periodo.setEditable(true);
        cmbx_periodo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmbx_periodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero - Junio", "Agosto - Diciembre", "Julio - Agosto" }));

        cmb_materia.setEditable(true);
        cmb_materia.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmb_materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programación orientada a objetos", "Estructura de datos", "Lenguajes de interfaz" }));

        cmb_grupo.setEditable(true);
        cmb_grupo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmb_grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISA", "ISB", "ISC", "ISD", "ISU" }));
        cmb_grupo.setToolTipText("");

        cmb_hora.setEditable(true);
        cmb_hora.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmb_hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00-08:00", "08:00-09:00", "09:00-10:00", "10:00-11:00", "11:00-12:00", "12:00-13:00", "13:00-14:00", "14:00-15:00", "15:00-16:00", "16:00-17:00", "17:00-18:00", "18:00-19:00", "19:00-20:00" }));
        cmb_hora.setToolTipText("");

        cmbx_anio.setEditable(true);
        cmbx_anio.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmbx_anio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020" }));

        txt_direccion_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccion_excelActionPerformed(evt);
            }
        });

        eti_cargar_lista.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_cargar_lista.setText("Cargar Lista:");

        btnAceptar.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        btnCancelar.setText("Regresar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(eti_titulo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eti_periodo)
                                .addComponent(eti_año)
                                .addComponent(eti_materia)
                                .addComponent(eti_grupo)
                                .addComponent(eti_hora))
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbx_periodo, 0, 191, Short.MAX_VALUE)
                                .addComponent(cmbx_anio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmb_materia, 0, 1, Short.MAX_VALUE)
                                .addComponent(cmb_grupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmb_hora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(eti_cargar_lista)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_direccion_excel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(eti_titulo)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_periodo)
                    .addComponent(cmbx_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_año)
                    .addComponent(cmbx_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_materia)
                    .addComponent(cmb_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eti_grupo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eti_hora))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_cargar_lista)
                    .addComponent(txt_direccion_excel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        //Creamos el objeto JFileChooser
        JFileChooser fc = new JFileChooser();

        //Indicamos lo que podemos seleccionar
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        //Creamos el filtro
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.xlsx", "xlsx");

        //Le indicamos el filtro
        fc.setFileFilter(filtro);

        //Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion = fc.showOpenDialog(jPanel1);

        //Si el usuario, pincha en aceptar
        if (seleccion == JFileChooser.APPROVE_OPTION) {

            //Seleccionamos el fichero
            File fichero = fc.getSelectedFile();

            //Ecribe la ruta del fichero seleccionado en el campo de texto
            txt_direccion_excel.setText(fichero.getAbsolutePath());
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Inicio menu = new Inicio();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txt_direccion_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccion_excelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccion_excelActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
            String carrera = "Ing. en Sistemas Computacionales";
            //String rutaArchivoExcel = "C:\\Users\\nga_a\\Documents\\NetBeansProjects\\pruebacalificaciones\\src\\Libro2.xlsx";
            String rutaArchivoExcel = txt_direccion_excel.getText();
            FileInputStream inputStream = new FileInputStream(new File(rutaArchivoExcel));
            Workbook workbook = new XSSFWorkbook(inputStream);
            Sheet firstSheet = workbook.getSheetAt(0);
            Iterator iterator = firstSheet.iterator();

            DataFormatter formatter = new DataFormatter();
            while (iterator.hasNext()) {
                Row nextRow = (Row) iterator.next();
                Iterator cellIterator = nextRow.cellIterator();
                String contenido[] = new String[2];
                Integer i = 0;
                while (cellIterator.hasNext()) {
                    Cell cell = (Cell) cellIterator.next();
                    String contenidoCelda = formatter.formatCellValue(cell);
                    //System.out.println("celda: " + contenidoCelda);
                    contenido[i] = contenidoCelda;
                    i++;
                }
                System.out.println(contenido[0]);
                System.out.println(contenido[1]);
                try {
                    con.insetarAlumno(contenido[0], contenido[1], carrera, "0", "", cmb_grupo.getSelectedItem().toString(), cmb_materia.getSelectedItem().toString(), cmbx_anio.getSelectedItem().toString(), cmbx_periodo.getSelectedItem().toString(), cmb_hora.getSelectedItem().toString());
                } catch (NullPointerException np) {

                }
            }
            JOptionPane.showMessageDialog(null, "Registro exitoso.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargar_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargar_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargar_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargar_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargar_lista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JComboBox<String> cmb_grupo;
    private javax.swing.JComboBox<String> cmb_hora;
    private javax.swing.JComboBox<String> cmb_materia;
    private javax.swing.JComboBox<String> cmbx_anio;
    private javax.swing.JComboBox<String> cmbx_periodo;
    private javax.swing.JLabel eti_año;
    private javax.swing.JLabel eti_cargar_lista;
    private javax.swing.JLabel eti_grupo;
    private javax.swing.JLabel eti_hora;
    private javax.swing.JLabel eti_materia;
    private javax.swing.JLabel eti_periodo;
    private javax.swing.JLabel eti_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_direccion_excel;
    // End of variables declaration//GEN-END:variables
}
