/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Martínez Hernández Gabriela
 *         Martínez Carrera Dulce Carolina
 */
public class Cargar_lista2 extends javax.swing.JFrame {

    /**
     * Creates new form cargar_lista
     */
    public Cargar_lista2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eti_carga_semestre = new javax.swing.JPanel();
        eti_titulo = new javax.swing.JLabel();
        eti_periodo = new javax.swing.JLabel();
        eti_carga_grupo = new javax.swing.JTextField();
        eti_materia = new javax.swing.JLabel();
        eti_grupo2 = new javax.swing.JLabel();
        eti_carga_materia = new javax.swing.JTextField();
        eti_grupo3 = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        eti_buscar_lista = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eti_titulo.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        eti_titulo.setText("Cargar Lista ");

        eti_periodo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_periodo.setText("Cargar lista para el grupo: ");

        eti_materia.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_materia.setText("la materia : ");

        eti_grupo2.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_grupo2.setText("del semestre: ");

        btn_buscar.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        btn_buscar.setText("Buscar");

        btn_aceptar.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        btn_aceptar.setText("Aceptar");

        btn_cancelar.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        btn_cancelar.setText("Cancelar");

        javax.swing.GroupLayout eti_carga_semestreLayout = new javax.swing.GroupLayout(eti_carga_semestre);
        eti_carga_semestre.setLayout(eti_carga_semestreLayout);
        eti_carga_semestreLayout.setHorizontalGroup(
            eti_carga_semestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eti_carga_semestreLayout.createSequentialGroup()
                .addGroup(eti_carga_semestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eti_carga_semestreLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(eti_carga_semestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(eti_carga_semestreLayout.createSequentialGroup()
                                .addComponent(eti_materia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eti_carga_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(eti_carga_semestreLayout.createSequentialGroup()
                                .addGroup(eti_carga_semestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(eti_carga_semestreLayout.createSequentialGroup()
                                        .addComponent(eti_grupo2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eti_grupo3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(eti_buscar_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(btn_buscar))))
                    .addGroup(eti_carga_semestreLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(eti_periodo)
                        .addGap(18, 18, 18)
                        .addComponent(eti_carga_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eti_carga_semestreLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btn_cancelar)
                        .addGap(117, 117, 117)
                        .addComponent(btn_aceptar))
                    .addGroup(eti_carga_semestreLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(eti_titulo)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        eti_carga_semestreLayout.setVerticalGroup(
            eti_carga_semestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eti_carga_semestreLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(eti_titulo)
                .addGap(35, 35, 35)
                .addGroup(eti_carga_semestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_periodo)
                    .addComponent(eti_carga_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(eti_carga_semestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(eti_carga_semestreLayout.createSequentialGroup()
                        .addGroup(eti_carga_semestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eti_materia)
                            .addComponent(eti_carga_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(eti_carga_semestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eti_grupo2)
                            .addComponent(eti_grupo3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(eti_buscar_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(eti_carga_semestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_aceptar))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eti_carga_semestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eti_carga_semestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargar_lista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargar_lista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargar_lista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargar_lista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargar_lista2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JTextField eti_buscar_lista;
    private javax.swing.JTextField eti_carga_grupo;
    private javax.swing.JTextField eti_carga_materia;
    private javax.swing.JPanel eti_carga_semestre;
    private javax.swing.JLabel eti_grupo2;
    private javax.swing.JTextField eti_grupo3;
    private javax.swing.JLabel eti_materia;
    private javax.swing.JLabel eti_periodo;
    private javax.swing.JLabel eti_titulo;
    // End of variables declaration//GEN-END:variables
}
