package vistas;

import Consultas.Consultas;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Martínez Hernández Gabriela Martínez Carrera Dulce Carolina
 */
public class Crear_grupo extends javax.swing.JFrame {

    Calendar calendario = Calendar.getInstance();
    Integer year = calendario.get(Calendar.YEAR);
    String[] nombreUsuarios;
    Consultas con = new Consultas();

    /**
     * Creates new form menu_grupo
     */
    public Crear_grupo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eti_titulo = new javax.swing.JLabel();
        eti_periodo = new javax.swing.JLabel();
        cmbx_periodo = new javax.swing.JComboBox<>();
        eti_materia = new javax.swing.JLabel();
        cmb_materia = new javax.swing.JComboBox<>();
        eti_grupo = new javax.swing.JLabel();
        cmb_grupo = new javax.swing.JComboBox<>();
        eti_hora = new javax.swing.JLabel();
        cmb_hora = new javax.swing.JComboBox<>();
        eti_num_unidad = new javax.swing.JLabel();
        cmb_unidad = new javax.swing.JComboBox<>();
        eti_año = new javax.swing.JLabel();
        txt_anio = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        etiquetaCurpMaestro = new javax.swing.JLabel();
        comboMaestros = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        eti_titulo.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        eti_titulo.setText("NUEVO GRUPO");

        eti_periodo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_periodo.setText("Periodo: ");

        cmbx_periodo.setEditable(true);
        cmbx_periodo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmbx_periodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero - Junio", "Agosto - Diciembre", "Julio - Agosto" }));

        eti_materia.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_materia.setText("Materia: ");

        cmb_materia.setEditable(true);
        cmb_materia.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmb_materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programación orientada a objetos", "Estructura de datos", "Lenguajes de interfaz", "Agregar otra..." }));
        cmb_materia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_materiaItemStateChanged(evt);
            }
        });
        cmb_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_materiaActionPerformed(evt);
            }
        });

        eti_grupo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_grupo.setText("Grupo:");

        cmb_grupo.setEditable(true);
        cmb_grupo.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmb_grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISA", "ISB", "ISC", "ISD", "ISU" }));
        cmb_grupo.setToolTipText("");

        eti_hora.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_hora.setText("Hora:");

        cmb_hora.setEditable(true);
        cmb_hora.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmb_hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00-08:00", "08:00-09:00", "09:00-10:00", "10:00-11:00", "11:00-12:00", "12:00-13:00", "13:00-14:00", "14:00-15:00", "15:00-16:00", "16:00-17:00", "17:00-18:00", "18:00-19:00", "19:00-20:00" }));
        cmb_hora.setToolTipText("");

        eti_num_unidad.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_num_unidad.setText("Num.Unidades");

        cmb_unidad.setEditable(true);
        cmb_unidad.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        cmb_unidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmb_unidad.setToolTipText("");

        eti_año.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        eti_año.setText("Año:");

        txt_anio.setEditable(false);

        btnCrear.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        btnCrear.setText("Crear ");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        etiquetaCurpMaestro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        etiquetaCurpMaestro.setText("Maestra/o:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(eti_periodo)
                                .addGap(58, 58, 58)
                                .addComponent(cmbx_periodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(eti_num_unidad)
                                        .addComponent(eti_año, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(eti_materia, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(eti_grupo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(eti_hora, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(etiquetaCurpMaestro))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_hora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_materia, 0, 251, Short.MAX_VALUE)
                                    .addComponent(txt_anio, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmb_unidad, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboMaestros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_grupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(eti_titulo)
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrear)
                .addGap(60, 60, 60)
                .addComponent(btnCancelar)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eti_titulo)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbx_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eti_periodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eti_año))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eti_materia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eti_grupo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_hora)
                    .addComponent(cmb_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eti_num_unidad)
                    .addComponent(cmb_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(etiquetaCurpMaestro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(comboMaestros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnCancelar))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_materiaActionPerformed

    }//GEN-LAST:event_cmb_materiaActionPerformed

    private void cmb_materiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_materiaItemStateChanged
        if (evt.getItem() == "Agregar otra...") {
            this.dispose();
            AgregarMateria agregarMateria = new AgregarMateria();
            agregarMateria.setVisible(true);
        }
    }//GEN-LAST:event_cmb_materiaItemStateChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        Inicio menuInicial = new Inicio();
        menuInicial.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
        txt_anio.setText(String.valueOf(year)); //Se cambia el año por el del sistema actual
        nombreUsuarios = con.getCurp();
        //Se rellena el combo box
        for (int i = 0; i < nombreUsuarios.length; i++) {
            comboMaestros.addItem(nombreUsuarios[i]);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
            con.insetarGrupo(cmb_grupo.getSelectedItem().toString(), cmb_materia.getSelectedItem().toString(), txt_anio.getText(), cmbx_periodo.getSelectedItem().toString(), cmb_unidad.getSelectedItem().toString(),cmb_hora.getSelectedItem().toString(), comboMaestros.getSelectedItem().toString());
            JOptionPane.showMessageDialog(null, "Registro exitoso.");
            Inicio menu = new Inicio();
            menu.setVisible(true);
            this.dispose();
        } catch (NullPointerException npe) {

        }
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_grupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox<String> cmb_grupo;
    private javax.swing.JComboBox<String> cmb_hora;
    private javax.swing.JComboBox<String> cmb_materia;
    private javax.swing.JComboBox<String> cmb_unidad;
    private javax.swing.JComboBox<String> cmbx_periodo;
    private javax.swing.JComboBox<String> comboMaestros;
    private javax.swing.JLabel eti_año;
    private javax.swing.JLabel eti_grupo;
    private javax.swing.JLabel eti_hora;
    private javax.swing.JLabel eti_materia;
    private javax.swing.JLabel eti_num_unidad;
    private javax.swing.JLabel eti_periodo;
    private javax.swing.JLabel eti_titulo;
    private javax.swing.JLabel etiquetaCurpMaestro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_anio;
    // End of variables declaration//GEN-END:variables
}
