/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Martínez Hernández Gabriela
 *         Martínez Carrera Dulce Carolina
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        msj = new javax.swing.JLabel();
        btn_cerrar_sesion = new javax.swing.JButton();
        barra_menu = new javax.swing.JMenuBar();
        menu_grupo = new javax.swing.JMenu();
        sub_crear_grupo = new javax.swing.JMenuItem();
        sep_1 = new javax.swing.JPopupMenu.Separator();
        sub_carga_lista = new javax.swing.JMenuItem();
        sep3 = new javax.swing.JPopupMenu.Separator();
        sub_ver_grupo = new javax.swing.JMenuItem();
        menu_materia = new javax.swing.JMenu();
        sub_ver_materia = new javax.swing.JMenuItem();
        sep1 = new javax.swing.JPopupMenu.Separator();
        sub_ver_calif = new javax.swing.JMenuItem();
        menuRubricas = new javax.swing.JMenu();
        verRubricas = new javax.swing.JMenuItem();
        insertarRubrica = new javax.swing.JMenuItem();
        editarRubrica = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msj.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        msj.setText("\"Bienvenido\"");

        btn_cerrar_sesion.setText("Cerrar sesión");
        btn_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar_sesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(msj)
                        .addGap(0, 159, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cerrar_sesion)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(msj, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(btn_cerrar_sesion)
                .addContainerGap())
        );

        menu_grupo.setText("Grupos");

        sub_crear_grupo.setText("Crear Grupo");
        sub_crear_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_crear_grupoActionPerformed(evt);
            }
        });
        menu_grupo.add(sub_crear_grupo);
        menu_grupo.add(sep_1);

        sub_carga_lista.setText("Cargar Listas");
        sub_carga_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_carga_listaActionPerformed(evt);
            }
        });
        menu_grupo.add(sub_carga_lista);
        menu_grupo.add(sep3);

        sub_ver_grupo.setText("Ver grupo");
        sub_ver_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_ver_grupoActionPerformed(evt);
            }
        });
        menu_grupo.add(sub_ver_grupo);

        barra_menu.add(menu_grupo);

        menu_materia.setLabel("Materias");

        sub_ver_materia.setText("Ver materias");
        sub_ver_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_ver_materiaActionPerformed(evt);
            }
        });
        menu_materia.add(sub_ver_materia);
        menu_materia.add(sep1);

        sub_ver_calif.setText("Ver calificaciones");
        sub_ver_calif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_ver_califActionPerformed(evt);
            }
        });
        menu_materia.add(sub_ver_calif);

        barra_menu.add(menu_materia);

        menuRubricas.setText("Rúbricas");

        verRubricas.setText("Ver rúbricas");
        verRubricas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verRubricasActionPerformed(evt);
            }
        });
        menuRubricas.add(verRubricas);

        insertarRubrica.setText("Insertar rúbrica");
        insertarRubrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarRubricaActionPerformed(evt);
            }
        });
        menuRubricas.add(insertarRubrica);

        editarRubrica.setText("Editar rúbrica");
        editarRubrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarRubricaActionPerformed(evt);
            }
        });
        menuRubricas.add(editarRubrica);

        barra_menu.add(menuRubricas);

        setJMenuBar(barra_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar_sesionActionPerformed
        this.dispose();
        Inicio_sesion login = new Inicio_sesion();
        login.setVisible(true);
    }//GEN-LAST:event_btn_cerrar_sesionActionPerformed

    private void sub_crear_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_crear_grupoActionPerformed
        this.dispose();
        Crear_grupo crear = new Crear_grupo();
        crear.setVisible(true);
    }//GEN-LAST:event_sub_crear_grupoActionPerformed

    private void sub_ver_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_ver_grupoActionPerformed
        this.dispose();
        Ver_grupo verGrupo = new Ver_grupo();
        verGrupo.setVisible(true);
    }//GEN-LAST:event_sub_ver_grupoActionPerformed

    private void sub_carga_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_carga_listaActionPerformed
        Cargar_lista cargarLista = new Cargar_lista();
        cargarLista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sub_carga_listaActionPerformed

    private void verRubricasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verRubricasActionPerformed
        this.dispose();
        VerRubrica rubrica = new VerRubrica();
        rubrica.setVisible(true);
    }//GEN-LAST:event_verRubricasActionPerformed

    private void insertarRubricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarRubricaActionPerformed
        this.dispose();
        InsertarRubrica insertaRubrica = new InsertarRubrica();
        insertarRubrica.setVisible(true);
    }//GEN-LAST:event_insertarRubricaActionPerformed

    private void sub_ver_califActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_ver_califActionPerformed
        this.dispose();
        VerCalificaciones cali = new VerCalificaciones();
        cali.setVisible(true);
    }//GEN-LAST:event_sub_ver_califActionPerformed

    private void sub_ver_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_ver_materiaActionPerformed
        this.dispose();
        VerMaterias verMateria = new VerMaterias();
        verMateria.setVisible(true);
    }//GEN-LAST:event_sub_ver_materiaActionPerformed

    private void editarRubricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarRubricaActionPerformed
        this.dispose();
        EditarRubrica editarRubricas = new EditarRubrica();
        editarRubricas.setVisible(true);
    }//GEN-LAST:event_editarRubricaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barra_menu;
    private javax.swing.JButton btn_cerrar_sesion;
    private javax.swing.JMenuItem editarRubrica;
    private javax.swing.JMenuItem insertarRubrica;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuRubricas;
    private javax.swing.JMenu menu_grupo;
    private javax.swing.JMenu menu_materia;
    private javax.swing.JLabel msj;
    private javax.swing.JPopupMenu.Separator sep1;
    private javax.swing.JPopupMenu.Separator sep3;
    private javax.swing.JPopupMenu.Separator sep_1;
    private javax.swing.JMenuItem sub_carga_lista;
    private javax.swing.JMenuItem sub_crear_grupo;
    private javax.swing.JMenuItem sub_ver_calif;
    private javax.swing.JMenuItem sub_ver_grupo;
    private javax.swing.JMenuItem sub_ver_materia;
    private javax.swing.JMenuItem verRubricas;
    // End of variables declaration//GEN-END:variables
}
